server:
  port: 8000
spring:
  application:
    name: currency-exchange
  jpa:
    showSql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true


# configure retry
resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s #set the interval between retry
        enableExponentialBackOff: true # increases wait time by its exponential
  #configure rate limiting
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  #configure bulkhead
  bulkhead:
    instances:
      sample-api:
        maxConcurrentCalls: 10

# configure tracing
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"